import {CategoryType, Product} from '../types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'اسپرسو 30 درصد عربیکا',
    subName: 'اسپرسو',
    price: 140000,
    // originalPrice: 0,
    // discountPercent: 0,
    rating: 4.8,
    image: '/product-img/1.jpg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، یک شات آب، کوکی مینی',
    volume: '۱۵۰ میلی‌لیتر'
  },
  {
    id: '2',
    name: 'اسپرسو 100 درصد عربیکا',
    subName: 'اسپرسو',
    price: 185000,
    rating: 4.5,
    image: '/product-img/2.jpg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، رستری ژاو مدل ورتکس، یک شات آب، کوکی مینی',
    volume: '۲۰۰ میلی‌لیتر'
  },
  {
    id: '3',
    name: 'امریکانو 30 درصد عربیکا',
    subName: 'امریکانو',
    price: 140000,
    // originalPrice: 110000,
    // discountPercent: 15,
    rating: 4.9,
    image: '/product-img/3.webp',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، آب جوش، کوکی مینی',
    volume: '۲۵۰ میلی‌لیتر'
  },
  {
    id: '4',
    name: 'آمریکانو 100 درصد عربیکا',
    subName: 'آمریکانو',
    price: 185000,
    rating: 4.7,
    image: '/product-img/4.jpg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، آب جوش، کوکی مینی',
    volume: '۶۰ میلی‌لیتر'
  },
  {
    id: '5',
    name: 'کاپوچینو 30 درصد عربیکا',
    subName: 'عربیکا',
    price: 185000,
    // originalPrice: 125000,
    // discountPercent: 22,
    rating: 4.6,
    image: '/product-img/5.jpg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، 170 میلی لیتر شیر و فوم شیر، کوکی مینی',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '6',
    name: 'کاپوچینو 100 درصد عربیکا',
    subName: 'عربیکا',
    price: 200000,
    // originalPrice: 100000,
    // discountPercent: 12,
    rating: 4.4,
    image: '/product-img/6.webp',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، 170 میلی لیتر شیر و فوم شیر، کوکی مینی',
    volume: '۲۴۰ میلی‌لیتر'
  },
  {
    id: '7',
    name: 'لاته 30 درصد عربیکا',
    subName: 'عربیکا',
    price: 215000,
    rating: 4.2,
    image: '/product-img/7.webp',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، 240 میلی لیتر شیر و فوم شیر، کوکی مینی',
    volume: '۳۰۰ میلی‌لیتر'
  },
  {
    id: '8',
    name: 'لاته 100 درصد عربیکا',
    subName: 'عربیکا',
    price: 230000,
    // originalPrice: 115000,
    // discountPercent: 17,
    rating: 4.8,
    image: '/product-img/8.jpg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، 240 میلی لیتر شیر و فوم شیر، کوکی مینی',
    volume: '۲۸۰ میلی‌لیتر'
  },
  {
    id: '9',
    name: 'لاته 30 درصد عربیکا + سیروپ',
    subName: 'عربیکا',
    price: 235000,
    rating: 4.7,
    image: '/product-img/9.webp',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، 240میلی لیتر شیر و فوم شیر، سیروپ دلخواه، کوکی مینی\n سیروپ (کارامل، شکلات، فندق، نارگیل، وانیل، لوتوس)',
    volume: '۱۸۰ میلی‌لیتر'
  },
  {
    id: '10',
    name: 'لاته 100 درصد عربیکا + سیروپ',
    subName: 'عربیکا',
    price: 250000,
    rating: 4.5,
    image: '/product-img/10.webp',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، 240میلی لیتر شیر و فوم شیر، سیروپ دلخواه، کوکی مینی\n سیروپ (کارامل، شکلات، فندق، نارگیل، وانیل، لوتوس)\n',
    volume: '۳۵۰ میلی‌لیتر'
  },
  {
    id: '11',
    name: 'کورتادو 30 درصد عربیکا',
    subName: 'کورتادو',
    price: 185000,
    rating: 4.6,
    image: '/product-img/11.jpeg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، نسبت مساوی شیر و اسپرسو، کوکی مینی',
    volume: '۱۲۰ میلی‌لیتر'
  },
  {
    id: '12',
    name: 'کورتادو 100 درصد عربیکا',
    subName: 'کورتادو',
    price: 200000,
    // originalPrice: 140000,
    // discountPercent: 21,
    rating: 4.9,
    image: '/product-img/11.jpeg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، نسبت مساوی شیر و اسپرسو، کوکی مینی',
    volume: '۳۰۰ میلی‌لیتر'
  },
  {
    id: '13',
    name: 'قهوه ترک',
    subName: 'قهوه ترک',
    price: 180000,
    rating: 4.3,
    image: '/product-img/13.webp',
    category: CategoryType.HOT_COFFEE,
    description: 'قهوه ترک 50درصد عربیکا، کوکی مینی',
    volume: '۷۰ میلی‌لیتر'
  },
  {
    id: '14',
    name: 'لاته 30 درصد عربیکا با شیر بادام / فندق',
    subName: 'لاته',
    price: 270000,
    rating: 4.7,
    image: '/product-img/14.jpeg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، شیر غیر لبنی بدون قند بادام / فندق، کوکی مینی',
    volume: '۲۴۰ میلی‌لیتر'
  },
  {
    id: '15',
    name: 'لاته 100 درصد عربیکا با شیر بادام / فندق',
    subName: 'لاته',
    price: 285000,
    rating: 4.6,
    image: '/product-img/15.jpg',
    category: CategoryType.HOT_COFFEE,
    description: 'دبل شات اسپرسو، شیر غیر لبنی بدون قند بادام / فندق، کوکی مینی',
    volume: '۲۰۰ میلی‌لیتر'
  },
  {
    id: '16',
    name: 'آیس آمریکانو 30 درصد عربیکا',
    subName: 'آیس آمریکانو',
    price: 145000,
    rating: 4.4,
    image: '/product-img/16.jpg',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، آب',
    volume: '۲۰۰ میلی‌لیتر'
  },
  {
    id: '17',
    name: 'آیس آمریکانو 100 درصد عربیکا',
    subName: 'آیس آمریکانو',
    price: 190000,
    rating: 4.5,
    image: '/product-img/17.jpg',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، آب',
    volume: '۲۵۰ میلی‌لیتر'
  },
  {
    id: '18',
    name: 'آیس لاته 30 درصد عربیکا',
    subName: 'آیس لاته',
    price: 220000,
    rating: 4.6,
    image: '/product-img/18.jpg',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، شیر',
    volume: '۹۰ میلی‌لیتر'
  },
  {
    id: '19',
    name: 'آیس لاته 100 درصد عربیکا',
    subName: 'آیس لاته',
    price: 235000,
    rating: 4.3,
    image: '/product-img/19.jpg',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، شیر',
    volume: '۳۲۰ میلی‌لیتر'
  },
  {
    id: '20',
    name: 'آیس لاته 30 درصد عربیکا + سیروپ',
    subName: 'آیس لاته',
    price: 240000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/20.jpg',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، شیر، سیروپ دلخواه سیروپ (کارامل، شکلات، فندق، نارگیل، وانیل، لوتوس)',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '21',
    name: 'آیس لاته 100 درصد عربیکا + سیروپ',
    subName: 'آیس لاته',
    price: 255000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/21.jpg',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، شیر، سیروپ دلخواه سیروپ (کارامل، شکلات، فندق، نارگیل، وانیل، لوتوس)',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '22',
    name: 'آفوگاتو 30 درصد عربیکا',
    subName: 'آفوگاتو',
    price: 230000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/22.webp',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، بستنی وانیل',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '23',
    name: 'آفوگاتو 100 درصد عربیکا',
    subName: 'آفوگاتو',
    price: 240000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/23.webp',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، بستنی وانیل',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '24',
    name: 'بلک هانی لمون 30 درصد عربیکا',
    subName: 'بلک هانی',
    price: 235000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/25.webp',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، عسل، لایم تازه، سودا',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '25',
    name: 'بلک هانی لمون 100 درصد عربیکا',
    subName: 'بلک هانی',
    price: 250000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/25.webp',
    category: CategoryType.COLD_COFFEE,
    description: 'دبل شات اسپرسو، یخ، عسل، لایم تازه، سودا',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '26',
    name: 'شیک لوتوس',
    subName: 'شیک',
    price: 275000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/26.jpg',
    category: CategoryType.MILKSHAKE,
    description: 'بستنی وانیل، شیر، کرم بیسکوییت، موز',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '27',
    name: 'شیک موز شکللات',
    subName: 'شیک',
    price: 275000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/27.jpg',
    category: CategoryType.MILKSHAKE,
    description: 'بستنی وانیل، شیر، شکلات، موز',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '28',
    name: 'شیک استراچاکلت',
    subName: 'شیک',
    price: 285000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/28.webp',
    category: CategoryType.MILKSHAKE,
    description: 'بستنی وانیل، شیر، توت فرنگی، شکلات',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '29',
    name: 'شیک بادام زمینی',
    subName: 'شیک',
    price: 285000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/29.webp',
    category: CategoryType.MILKSHAKE,
    description: 'بستنی وانیل، شیر، کره بادام زمینی کرانچی، موز، کمی کارامل',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '200',
    name: 'شیک تیرامیسو',
    subName: 'شیک',
    price: 280000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/200.jpg',
    category: CategoryType.MILKSHAKE,
    description: 'بستنی وانیل، شیر، اسپرسو، کاکائو، بیسکوییت، پنیر',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '30',
    name: 'هات چاکلت',
    subName: 'هات',
    price: 210000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/30.webp',
    category: CategoryType.HOT_DRINKS,
    description: 'شیر، شکلات داغ',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '31',
    name: 'نسکافه',
    subName: 'هات',
    price: 185000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/31.webp',
    category: CategoryType.HOT_DRINKS,
    description: 'شیر، پودر کاپوچینو پرمیوم',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '32',
    name: 'چای ماسالا',
    subName: 'هات',
    price: 185000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/32.webp',
    category: CategoryType.HOT_DRINKS,
    description: 'شیر، پودر ماسالا',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '33',
    name: 'نوشیدنی بیسکاتی',
    subName: 'هات',
    price: 210000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/33.jpg',
    category: CategoryType.HOT_DRINKS,
    description: 'شیر، کرم بیسکوییت',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '34',
    name: 'چای لاته کاراملی',
    subName: 'هات',
    price: 185000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/34.webp',
    category: CategoryType.HOT_DRINKS,
    description: 'شیر، پودر چای، پودر شیر غیر لبنی،  کارامل، شکر',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '35',
    name: 'وایت نات چاکلت',
    subName: 'هات',
    price: 215000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/35.webp',
    category: CategoryType.HOT_DRINKS,
    description: 'شیر، کره بادام زمینی، پودر وایت چاکلت',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '36',
    name: 'چای سیاه',
    subName: 'چایی',
    price: 110000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/36.webp',
    category: CategoryType.TEA_HERBAL_TEA,
    description: 'چای ساده، قند، نبات',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '37',
    name: 'رویبوس بی انتها',
    subName: 'رویبوس',
    price: 150000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/37.webp',
    category: CategoryType.TEA_HERBAL_TEA,
    description: 'ترکیبات: رویبوس، تکه های سیب، کشمش، برگ های انگور وحشی، تخم گشنیز عطر و بو: ترشی مرکبات، شیرین و چوبی طعم: شیرین، ملایم، میوه ای، مرکبات',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '38',
    name: 'رویبوس رویای آفریقایی',
    subName: 'رویبوس',
    price: 150000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/38.webp',
    category: CategoryType.TEA_HERBAL_TEA,
    description: 'ترکیبات: رویبوس، سیب، یاسمین، وانیل عطر و بو: شیرین، وانیل، کارامل طعم: ملایم و میوه ای',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '39',
    name: 'دمنوش انرژی',
    subName: 'دمنوش',
    price: 165000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/39.jpeg',
    category: CategoryType.TEA_HERBAL_TEA,
    description: 'ترکیبی انرژی‌بخش با طعم قوی و میوه‌ای هلو و زنجبیل. از جمله مواد تشکیل‌دهنده، رویبوس (اسفالاتوس لینئاریس)، گوارانا و ریشه زنجبیل.',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '40',
    name: 'دمنوش آرامش',
    subName: 'دمنوش',
    price: 165000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/40.webp',
    category: CategoryType.TEA_HERBAL_TEA,
    description: 'ترکیبی از گیاهان با خواص آرام‌بخش از جمله بابونه، رازیانه، گل و برگ‌های درخت لیمو، پوست بید سفید، مرزنجوش، بادرنجبویه، نعناع فلفلی، گل ساعتی، گل و برگ‌های زالزالک، اسطوخودوس، وودراف (گیاه معطر).رایحه/عطر: عطر شیرین غالب لیمو و بابونه، همراه با نت‌های علفی',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '41',
    name: 'سانتا ماریا',
    subName: 'سانتا',
    price: 155000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/41.webp',
    category: CategoryType.TEA_HERBAL_TEA,
    description: 'ترکیبات: چای سیاه کنگو، گل رز چینی، چای سیاه مارینین کنیا، ورسک، گلبرگ های رز، انگور فرنگی، گلبرگ های آفتابگردان عطر و بو: عطر قوی و شیرین انگور همراه با نت های گیلاس و توت فرنگی طعم: ملایم، غیر ترش و میوه ای',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '42',
    name: 'بهشت',
    subName: 'بهشت',
    price: 125000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/42.webp',
    category: CategoryType.TEA_HERBAL_TEA,
    description: 'نسبتا شیرین، گل محمدی، دارچین، سیب، به، دارچین، بهار نارنج',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '43',
    name: 'موهیتو',
    subName: 'موهیتو',
    price: 180000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/43.jpg',
    category: CategoryType.COLD_DRINKS,
    description: 'یخ کراش، نعنا موهیتو، لیمو ترش، سیروپ شکر، سودا',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '44',
    name: 'لیموناد',
    subName: 'لیموناد',
    price: 170000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/44.jpeg',
    category: CategoryType.COLD_DRINKS,
    description: 'یخ کراش، لیمو ترش، سیروپ شکر، سودا',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '45',
    name: 'فراپه لیمو توت فرنگی',
    subName: 'فراپه',
    price: 230000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/45.jpg',
    category: CategoryType.COLD_DRINKS,
    description: 'یخ کراش، بستنی، سیروپ توت فرنگی، توت فرنگی منجمد، لیمو ترش',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '46',
    name: 'فراپاچینو قهوه کارامل',
    subName: 'فراپه',
    price: 230000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/46.webp',
    category: CategoryType.COLD_DRINKS,
    description: 'یخ کراش، بستنی، سیروپ کارامل، اسپرسو',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '47',
    name: 'ریفرشر توت فرنگی',
    subName: 'ریفرشر',
    price: 210000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/46.jpg',
    category: CategoryType.COLD_DRINKS,
    description: 'سودا، یخ، سیروپ دست ساز توت فرنگی، کمی لیمو ترش، نارگیل',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '48',
    name: 'ریفرشر کیوی',
    subName: 'ریفرشر',
    price: 210000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '',
    category: CategoryType.COLD_DRINKS,
    description: 'سودا، یخ، سیروپ دست ساز کیوی، کمی لیو ترش، آناناس',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '49',
    name: 'براونی ماربل',
    subName: 'براونی',
    price: 200000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/49.webp',
    category: CategoryType.CAKE,
    description: 'براونی شکلاتی با یک لایه پنیر',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '50',
    name: 'کیک هویج',
    subName: 'کیک',
    price: 180000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/50.webp',
    category: CategoryType.CAKE,
    description: 'کیک اسفنجی با تکه های هویج',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '51',
    name: 'چیزکیک سن سباستین',
    subName: 'چیزکیک',
    price: 230000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '',
    category: CategoryType.CAKE,
    description: 'یک اسلایس چیز کیک سن سباستین',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '52',
    name: 'کروسان شکلاتی',
    subName: 'کروسان',
    price: 230000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/52.webp',
    category: CategoryType.CAKE,
    description: 'کروسان کره ای، پر شده با سس شکلات',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '53',
    name: 'پنینی چیکن باربیکیو',
    subName: 'پنینی',
    price: 385000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/53.jpg',
    category: CategoryType.SNACKS,
    description: 'نان چیاباتا، سینه مرغ گریل شده، پنیر پیتزا، سس باربیکیو مخصوص',
    volume: '۲۲۰ میلی‌لیتر'
  },
  {
    id: '54',
    name: 'سیب زمینی پنیری',
    subName: 'سیب زمینی',
    price: 285000,
    // originalPrice: 110000,
    // discountPercent: 16,
    rating: 4.5,
    image: '/product-img/54.webp',
    category: CategoryType.SNACKS,
    description: '350گرم سیب زمینی سرخ شده (بدون روغن)، پنیر پیتزا',
    volume: '۲۲۰ میلی‌لیتر'
  },
];
